name: test auction
on:
  workflow_dispatch:
    inputs:
      docker-tag:
        description: 'Tag for the Docker image'
        required: true
        default: 'latest'

jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
    - name: testing
      run: echo "hi da venna"
