name: test auction
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to (staging or qa)'
        required: true
        default: 'staging'
jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
    - name: testing
      run: echo "hi da venna"
